### ISSUE TITLE
Gui display the current number of blue fish

### ISSUE THREAD

**Issue by ErencanPelin** [ErencanPelin/CG-Group-Project#28]
Might be cool to have a gui display the current number of blue fish (this number already exists in the code in the main.js script, just need to put it on the screen)

**Comment by iasadk** [comment]
Is the number of red and blue fishes are decreasing or increasing over some time period ?? Can you please explain ??
As I'm trying to understand the code and as Im looking the total blue fish are 2000 and red fish are 100.

**Comment by ErencanPelin** [comment]
> Is the number of red and blue fishes are decreasing or increasing over some time period ?? Can you please explain ?? As I'm trying to understand the code and as Im looking the total blue fish are 2000 and red fish are 100.

Hey! Thanks for reaching out, sadly this is a university project and so we're not allowed to accept any outside help!

**Comment by iasadk** [comment]
oh ok, no problem :)
